on:
  workflow_call:
    inputs:
      ref:
        description: Release commit reference
        required: true
        type: string
      publish:
        description: Publish image to the registry
        default: true
        required: true
        type: boolean
    secrets:
      DOCKERHUB_TOKEN:
        required: true
  workflow_dispatch: {}

jobs:
  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta ghcr.io
        id: meta2
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=semver,pattern={{version}},value=${{ inputs.ref }}

      - name: Build and push to ghcr.io
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm,linux/arm64,
          push: ${{ inputs.publish }}
          tags: ${{ steps.meta2.outputs.tags }}
          labels: ${{ steps.meta2.outputs.labels }}
          build-args: |
            node_env=production
